name: Deploy Lambda Function

on:
  push:
  branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create Zip file for Lambda Function
        run: apt-get update && apt-get install -y zip && zip -r code.zip *
      - name: AWS CLI v2
        uses: imehedi/actions-aws-cli@v2
        with:
          args: lambda update-function-code
          --function-name ${{ secrets.FUNCTION_NAME }}
          --zip-file fileb://code.zip

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
