name: Deploy Lambda Function

on: [push]

jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Build binary
        run: |
          sudo apt update && sudoe apt install -y zip && sudo zip -r code.zip *
      - name: default deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          function_name: hello-hunter-dynamic-dialer-weekly-reload
          zip_file: code.zip
